### ISSUE TITLE
What is the current status of using this crate as a client?

### ISSUE THREAD

**Issue by notgull** [Riey/xim-rs#37]
I'd like to be able to use this crate for IME handling in `winit` (see rust-windowing/winit#2614). However, it seems like client support in this crate is still relatively immature. From looking, I see that there are a handful of `todo`s in `client.rs`.

What is the current status of this crate's client API? Is there anything I can do to make this more suitable as a client?

**Comment by Riey** [comment]
> What is the current status of this crate's client API?

I made this crate for my IME so client side usage is second option.
Its functionality is almost done but could have several bugs and API is still remains question.

> Is there anything I can do to make this more suitable as a client?

You can try and find bugs in client
There is simple client example https://github.com/Riey/xim-rs/blob/master/examples/x11rb_client.rs which can test with other servers like ibus or etc.

Just note that I don't have much time for working this project. Bug fix can be slow.

**Comment by notgull** [comment]
Okay, thanks! I'll open issues as I find them (e.g. #39).
